### ISSUE TITLE
Need Help for Translate?

### ISSUE THREAD

**Issue by AlperAkca79** [jpbandroid/UltraTextEdit-UWP#7]
If you need help to translate Turkish I can help you.

**Comment by jpbandroid** [comment]
ok thx. but if you want to help me translate, either wait for me to implement translations (I can tell you, it is hard), or help me translate the UltraTextEdit UWP 22H2+ project.
Here's the link if you want to help me there `https://github.com/jpbandroid/UltraTextEdit-UWP-22H2`

**Comment by AlperAkca79** [comment]
@jpbandroid  Yeah I want to help you to translate ![UltraTextEdit UWP 22H2+](https://github.com/jpbandroid/UltraTextEdit-UWP-22H2) project.

**Comment by AlperAkca79** [comment]
@jpbandroid Where and when do I start?
